### PR TITLE
UCSBSubjects Page Placeholders

### LINKED ISSUE #13: Add UCSBSubjects menu and page placeholders
Add UCSBSubjects menu and page placeholders

The menu shows up only when logged in.  It has only one item for regular users (List) and two items for Admin users (List and Create). These links go to placeholder pages UCSBSubjectIndexPage and UCSBSubjectsCreatePage.

You can use the menu for Todos and the placeholder pages for Todos (already in the repo) as models.

# Navbar related Acceptance Criteria

- [x] There is a menu item UCSBSubjects (this is done on the Navbar)
- [x] The menu item on the navbar only shows up when you are logged in.
- [x] It has two items for Admins, List and Create
- [x] It has one item for regular Users, List
- [x] List routes to  `/ucsbsubjects/list`
- [x] Create routes to  `/ucsbsubjects/create`

# Page related acceptance criteria

- [x] There are pages components under `/frontend/src/main/pages/UCSBSubjects/` similar to those under `/frontend/src/main/pages/Todos/` for the create and index pages.
- [x] There are entries for these pages in the storybook.
- [x] The List placeholder page is available at `/ucsbsubjects/list` (this is done in `App.js`)
- [x] The Create placeholder page is available at `/ucsbsubjects/create` (this is done in `App.js`)

### PR DESCRIPTION
**Pull request by mglush**
# Overview
In this PR we add placeholder pages for UCSBSubjects. For admins, the navbar shows 2 components for UCSBSubjects (list, create), and for users, the navbar shows 1 component (list). The buttons route to /ucsbsubjects/list and /ucsbsubjects/create, respectively.

Screen Shot 2022-02-17 at 3 28 27 PM

## Reminders (delete this section before merging or as code is merged)
- [x] Explicitly link to this pull request each issue that it closes
- [x] Assign one and ideally two reviewers to review this pull request. 
- [x] Reviewers should not just approve with "Looks good!" Instead, reviewers should carefully go through the code and use GitHub's reviewer interface to ask questions, make comments, and suggest changes.

### CODE REVIEW

**Review by vChase42 — CHANGES_REQUESTED** [review]
When clicking the List and Create buttons, the page redirects to the correct link, but it's a blank page with nothing.
On storybook there is no page thing for UCSBSubject

image

Otherwise looks good

**Comment by mglush** [comment]
Fixed storybook component:

Screen Shot 2022-02-18 at 10 34 26 AM

**Comment by vChase42** [comment]
LGTM

**Comment by mglush** [comment]
Just increased the timeout variable in the stryker config javascript file so that npx stryker mutation testing doesnt time out.

**Review by vChase42 — APPROVED** [review]

**Review by vChase42 — CHANGES_REQUESTED** [review]
Extra file causes storybook to not build properly
image

**Review by thomashale-ucsb — COMMENTED** [review]
Coverage tests, regular tests, localhost spring-boot testing, and heroku testing works, however npx stryker run gives me a mutation score of only 98.59, advise if this is acceptable or not

**Comment by vChase42** [comment]
> Coverage tests, regular tests, localhost spring-boot testing, and heroku testing works, however npx stryker run gives me a mutation score of only 98.59, advise if this is acceptable or not

image
Seems to be linked to lines 104-105 of AppNavbar.js

**Comment by mglush** [comment]
removed the 'UCSBdates copy' folder, added mutation tests for the navbar. to test lines 104-105 causing stryker to get less than 100%. should be fixed now. apologies.

**Pull request merged**
