### PR TITLE
sc - added purge which deletes all earthquakes in collection

### LINKED ISSUE #23: Add endpoint to purge earthquakes
Add endpoint to purge earthquakes

# ACs

- [x] In Swagger, there is an api endpoint `POST /api/earthquakes/purge` accessible only to admins that deletes all earthquakes from the `earthquakes` collection.

### PR DESCRIPTION
**Pull request by stychoi**
# Overview

added POST api endpiont for purge that's only accessible to admins

# Issues Addressed

Closes #23 

# Details

Screen Shot 2022-02-23 at 1 02 47 PM

After purging, no earthquakes are shown when executing list all:
Screen Shot 2022-02-23 at 1 02 58 PM

## Reminders (delete this section before merging or as code is merged)
- [x] Explicitly link to this pull request each issue that it closes
- [x] Assign one and ideally two reviewers to review this pull request. 
- [x] Reviewers should not just approve with "Looks good!" Instead, reviewers should carefully go through the code and use GitHub's reviewer interface to ask questions, make comments, and suggest changes.

### CODE REVIEW

**Review by mglush — CHANGES_REQUESTED** [review]
need to write test coverage for earfquake controlla

**Comment by stychoi** [comment]
Oh woops I forgot to add tests, got a bit ahead of myself

**Comment by stychoi** [comment]
added tests

**Review by mglush — APPROVED** [review]
LGTM

**Pull request merged**
