### PR TITLE
Th collegiate subreddits list page

### LINKED ISSUE #8: Implement List page for CollegiateSubreddits
Implement List page for CollegiateSubreddits 

Implement the List page using the Table component made in a previous issue.  For now, no need for the Edit and Delete columns (those will come later). 

You may use the UCSBStudentsIndexPage as a model.

- [x] When loading the page, it fetches data from the backend and populates the table
- [x] test coverage is 100% for `npm run coverage`
- [x] test coverage is 100% for `npx stryker run`

### PR DESCRIPTION
**Pull request by thomashale-ucsb**
# Overview

Frontend functionality for collegiate subreddits finished

# Details

localhost:8080 functionality:
Screen Shot 2022-02-22 at 12 01 53 AM

heroku-qa functionality:
Screen Shot 2022-02-22 at 12 10 20 AM

stryker frontend mutation tests done:
Screen Shot 2022-02-22 at 12 16 32 AM

## Reminders (delete this section before merging or as code is merged)
- [x] Explicitly link to this pull request each issue that it closes
- [x] Assign one and ideally two reviewers to review this pull request. 
- [ ] Reviewers should not just approve with "Looks good!" Instead, reviewers should carefully go through the code and use GitHub's reviewer interface to ask questions, make comments, and suggest changes.

### CODE REVIEW

**Review by isaacchin — APPROVED** [review]
Tested it on localhost:8080 and Heroku QA, and it works. Test coverage seems good as well.

**Comment by thomashale-ucsb** [comment]
Note this might not work if we reformat all references to collegiate_subreddits to collegiatesubreddits as planned

**Comment by vChase42** [comment]
I almost managed to add a commit to this branch that allows it to be merged with main but my internet is crapping out on this train.
Just do a “git pull origin main” , replace the final instances of collegiate_subreddits with collegiatesubreddits, and fix a merge issue with collegiate fixtures

**Comment by xiyuewang556633** [comment]
Screen Shot 2022-02-22 at 6 18 47 PM
Error encountered when I try to run locally, the list is empty

**Review by XYWayne — CHANGES_REQUESTED** [review]
Screen Shot 2022-02-22 at 6 18 47 PM
Something wrong happened when I tested it locally, it seemed the list was empty

**Review by vChase42 — APPROVED** [review]
LGTM

**Pull request merged**
